name: CI/CD for Backend

on:
  push:
    branches: [main, DevOps, Dev]
  pull_request:
    branches: [main, DevOps, Dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Print Environment Variables
        run: |
          echo DB_HOST=${{ secrets.DB_HOST }}
          echo DB_NAME=${{ secrets.DB_NAME }}
          echo SECRET_KEY=${{ secrets.SECRET_KEY }}
          echo MA_USER=${{ secrets.MA_USER }}
          echo MA_PASSWORD=${{ secrets.MA_PASSWORD }}
          echo MA_SERVER=${{ secrets.MA_SERVER }}

      - name: Run Tests
        env: # Define your environment variables here
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          MA_USER: ${{ secrets.MA_USER }}
          MA_PASSWORD: ${{ secrets.MA_PASSWORD }}
          MA_SERVER: ${{ secrets.MA_SERVER }}
        run: npm test
